INSERT INTO [tbl_SysPrivs1]([Id],[Name],[SortId],[IsEnable],[ClassName]) VALUES (1,'组团团队',0,'1','zutuan')
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (1,1,'团队报价','/TeamCenter/PriceList.aspx?sl=1&type=1',0,'1')	
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (1,1,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (2,1,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (3,1,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (4,1,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (5,1,'删除',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (6,1,'取消',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (7,1,'报价成功',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (2,1,'派团计划','/TeamCenter/TeamplanList.aspx?sl=2&type=1',0,'1')	
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (8,2,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (9,2,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (10,2,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (11,2,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (12,2,'删除',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (13,2,'取消',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (14,2,'派团给计调',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (3,1,'组团散拼','/TeamCenter/SanpinList.aspx?sl=3&type=1',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (15,3,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (16,3,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (17,3,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (18,3,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (19,3,'删除',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (20,3,'取消',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (21,3,'审核',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (22,3,'派团给计调',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (23,3,'订单报名',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (24,3,'处理订单',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (4,1,'销售收款','/TeamCenter/SalesReceivablesList.aspx?sl=4&type=1',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (25,4,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (26,4,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (27,4,'确认合同金额',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (28,4,'收款',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (29,4,'退款',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (30,4,'查看当日收款',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (5,1,'销售报账','/TeamCenter/SalesAccountList.aspx?sl=5&type=1',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (31,5,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (32,5,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (33,5,'销售报账操作',0,'1')
		
		
		
INSERT INTO [tbl_SysPrivs1]([Id],[Name],[SortId],[IsEnable],[ClassName]) VALUES (2,'地接团队',0,'1','diejietd')
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (6,2,'团队报价','/TeamCenter/PriceList.aspx?sl=6&type=2',0,'1')	
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (34,6,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (35,6,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (36,6,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (37,6,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (38,6,'删除',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (39,6,'取消',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (40,6,'报价成功',0,'1')
	
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (7,2,'派团计划','/TeamCenter/TeamplanList.aspx?sl=7&type=2',0,'1')	
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (41,7,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (42,7,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (43,7,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (44,7,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (45,7,'删除',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (46,7,'取消',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (47,7,'派团给计调',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (8,2,'地接散拼','/TeamCenter/SanpinList.aspx?sl=8&type=2',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (48,8,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (49,8,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (50,8,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (51,8,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (52,8,'删除',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (53,8,'取消',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (54,8,'审核',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (55,8,'派团给计调',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (56,8,'订单报名',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (57,8,'处理订单',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (9,2,'销售收款','/TeamCenter/SalesReceivablesList.aspx?sl=9&type=2',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (58,9,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (59,9,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (60,9,'确认合同金额',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (61,9,'收款',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (62,9,'退款',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (63,9,'查看当日收款',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (10,2,'销售报账','/TeamCenter/SalesAccountList.aspx?sl=10&type=2',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (64,10,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (65,10,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (66,10,'销售报账操作',0,'1')
		

		
INSERT INTO [tbl_SysPrivs1]([Id],[Name],[SortId],[IsEnable],[ClassName]) VALUES (3,'出境团队',0,'1','cjtd')
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (11,3,'团队报价','/TeamCenter/PriceList.aspx?sl=11&type=3',0,'1')	
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (67,11,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (68,11,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (69,11,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (70,11,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (71,11,'删除',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (72,11,'取消',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (73,11,'报价成功',0,'1')
	
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (12,3,'派团计划','/TeamCenter/TeamplanList.aspx?sl=12&type=3',0,'1')	
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (74,12,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (75,12,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (76,12,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (77,12,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (78,12,'删除',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (79,12,'取消',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (80,12,'派团给计调',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (13,3,'出境散拼','/TeamCenter/SanpinList.aspx?sl=13&type=3',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (81,13,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (82,13,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (83,13,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (84,13,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (85,13,'删除',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (86,13,'取消',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (87,13,'审核',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (88,13,'派团给计调',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (89,13,'订单报名',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (90,13,'处理订单',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (14,3,'销售收款','/TeamCenter/SalesReceivablesList.aspx?sl=14&type=3',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (91,14,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (92,14,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (93,14,'确认合同金额',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (94,14,'收款',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (95,14,'退款',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (96,14,'查看当日收款',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (15,3,'销售报账','/TeamCenter/SalesAccountList.aspx?sl=15&type=3',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (97,15,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (98,15,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (99,15,'销售报账操作',0,'1')
		



INSERT INTO [tbl_SysPrivs1]([Id],[Name],[SortId],[IsEnable],[ClassName]) VALUES (4,'同业分销',0,'1','tongyefx')
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (16,4,'收客计划','/SellCenter/CustomerPlan/CustomerPlan.aspx?sl=16',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (100,16,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (101,16,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (102,16,'订单报名',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (17,4,'订单中心','/SellCenter/Order/OrderList.aspx?sl=17',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (103,17,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (104,17,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (105,17,'处理订单',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (18,4,'销售收款','/SellCenter/Sell/SellIncome.aspx?sl=18',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (106,18,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (107,18,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (108,18,'确认合同金额',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (109,18,'收款',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (110,18,'退款',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (111,18,'查看当日收款',0,'1')
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (90,4,'批量销账','javascript:void(0)',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (421,90,'栏目',0,'1','1')
		
		
INSERT INTO [tbl_SysPrivs1]([Id],[Name],[SortId],[IsEnable],[ClassName]) VALUES (5,'单项业务',0,'1','dxyw')
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (19,5,'单项业务','javascript:void(0)',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (112,19,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (113,19,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (114,19,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (115,19,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (116,19,'删除',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (117,19,'提交账务',0,'1')
		
INSERT INTO [tbl_SysPrivs1]([Id],[Name],[SortId],[IsEnable]) VALUES (6,'无计划散客',0,'1')
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (20,6,'无计划散客','javascript:void(0)',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (118,20,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (119,20,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (120,20,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (121,20,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (122,20,'删除',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (123,20,'取消',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (124,20,'提交账务',0,'1')
		

INSERT INTO [tbl_SysPrivs1]([Id],[Name],[SortId],[IsEnable],[ClassName]) VALUES (7,'计调中心',0,'1','jidiaozx')
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (21,7,'组团计调','/OperaterCenter/TeamOperaterList.aspx?sl=21',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (125,21,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (126,21,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (127,21,'安排酒店',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (128,21,'安排用车',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (129,21,'安排景点',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (130,21,'安排游轮',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (131,21,'安排地接',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (132,21,'安排用餐',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (133,21,'安排购物',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (134,21,'安排领料',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (135,21,'安排大交通',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (136,21,'安排导游',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (137,21,'安排其它',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (138,21,'备用金申请',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (139,21,'预付申请',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (140,21,'单团核算',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (141,21,'计调报账',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (142,21,'打印出团通知单',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (143,21,'打印导游任务单',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (22,7,'地接计调','/OperaterCenter/AgencyOperaterList.aspx?sl=22',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (144,22,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (145,22,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (146,22,'安排酒店',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (147,22,'安排用车',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (148,22,'安排景点',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (149,22,'安排游轮',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (150,22,'安排地接',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (151,22,'安排用餐',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (152,22,'安排购物',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (153,22,'安排领料',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (154,22,'安排大交通',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (155,22,'安排导游',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (156,22,'安排其它',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (157,22,'备用金申请',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (158,22,'预付申请',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (159,22,'单团核算',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (160,22,'计调报账',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (161,22,'打印出团通知单',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (162,22,'打印导游任务单',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (23,7,'出境计调','/OperaterCenter/DeparOperaterList.aspx?sl=23',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (163,23,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (164,23,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (165,23,'安排酒店',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (166,23,'安排用车',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (167,23,'安排景点',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (168,23,'安排游轮',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (169,23,'安排地接',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (170,23,'安排用餐',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (171,23,'安排购物',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (172,23,'安排领料',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (173,23,'安排大交通',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (174,23,'安排导游',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (175,23,'安排签证',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (176,23,'安排其它',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (177,23,'备用金申请',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (178,23,'预付申请',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (179,23,'单团核算',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (180,23,'计调报账',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (181,23,'打印出团通知单',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (182,23,'打印导游任务单',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (24,7,'业务变更','/OperaterCenter/OperationChange.aspx?sl=24',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (183,24,'栏目',0,'1','1')
	
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (25,7,'计调报账','/OperaterCenter/OperaReimbursement.aspx?sl=25',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (184,25,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (185,25,'查看全部',0,'1')
		
	
	
	
INSERT INTO [tbl_SysPrivs1]([Id],[Name],[SortId],[IsEnable],[ClassName]) VALUES (8,'导游中心',0,'1','daoyouzx')
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (26,8,'导游档案','/GuideCenter/GuideRecord.aspx?sl=26',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (186,26,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (187,26,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (188,26,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (189,26,'删除',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (27,8,'导游排班','/GuideCenter/GuideSchedul.aspx?sl=27',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (190,27,'栏目',0,'1','1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (28,8,'导游报账','/GuideCenter/GuidReimbursement.aspx?sl=28',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (191,28,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (192,28,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (193,28,'导游报账操作',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (93,8,'上团统计','/GuideCenter/GuiTourStatistics.aspx?sl=93',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (437,93,'栏目',0,'1','1')
		
INSERT INTO [tbl_SysPrivs1]([Id],[Name],[SortId],[IsEnable],[ClassName]) VALUES (9,'资源预控',0,'1','ziyuanyk')	
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (29,9,'酒店预控','/ResourceCenter/Tavern/List.aspx?sl=29',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (194,29,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (195,29,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (196,29,'预控变更',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (30,9,'车辆预控','/ResourceCenter/Car/List.aspx?sl=30',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (197,30,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (198,30,'新增',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (31,9,'游船预控','/ResourceCenter/LoosePulley/List.aspx?sl=31',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (199,31,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (200,31,'新增',0,'1')
		

INSERT INTO [tbl_SysPrivs1]([Id],[Name],[SortId],[IsEnable],[ClassName]) VALUES (10,'质量管理',0,'1','zilianggl')	
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (32,10,'团队回访','/QualityCenter/TeamVisit/VisitList.aspx?sl=32',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (201,32,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (202,32,'登记',0,'1')
	
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (33,10,'投诉管理','/QualityCenter/Complaint/CompList.aspx?sl=33',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (203,33,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (204,33,'登记',0,'1')

INSERT INTO [tbl_SysPrivs1]([Id],[Name],[SortId],[IsEnable],[ClassName]) VALUES (11,'客户管理',0,'1','kehugl')	
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (34,11,'同行客户','/CustomerCenter/Same/CustomerList.aspx?sl=34',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (205,34,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (206,34,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (207,34,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (208,34,'删除',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (35,11,'单位直客','/CustomerCenter/Unit/CustomerList.aspx?sl=35',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (209,35,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (210,35,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (211,35,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (212,35,'删除',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (36,11,'个人会员','/CustomerCenter/Member/MemberList.aspx?sl=36',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (213,36,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (214,36,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (215,36,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (216,36,'删除',0,'1')
		

		

INSERT INTO [tbl_SysPrivs1]([Id],[Name],[SortId],[IsEnable],[ClassName]) VALUES (12,'资源管理',0,'1','ziyuangl')	
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (37,12,'地接社','/ResourceManage/Ground/GroundList.aspx?sl=37',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (217,37,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (218,37,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (219,37,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (220,37,'删除',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (221,37,'导入',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (222,37,'导出',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (38,12,'酒店','/ResourceManage/Wineshop/WineshopList.aspx?sl=38',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (223,38,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (224,38,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (225,38,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (226,38,'删除',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (227,38,'导入',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (228,38,'导出',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (39,12,'餐馆','/ResourceManage/Hotle/HotleList.aspx?sl=39',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (229,39,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (230,39,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (231,39,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (232,39,'删除',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (233,39,'导入',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (234,39,'导出',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (40,12,'游轮','/ResourceManage/Cruise/CruiseList.aspx?sl=40',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (235,40,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (236,40,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (237,40,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (238,40,'删除',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (239,40,'导入',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (240,40,'导出',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (41,12,'车队','/ResourceManage/Car/CarList.aspx?sl=41',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (241,41,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (242,41,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (243,41,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (244,41,'删除',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (245,41,'导入',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (246,41,'导出',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (42,12,'票务','/ResourceManage/Ticket/TicketList.aspx?sl=42',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (247,42,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (248,42,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (249,42,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (250,42,'删除',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (251,42,'导入',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (252,42,'导出',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (43,12,'景点','/ResourceManage/ScenicSpots/ScenicSpotsList.aspx?sl=43',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (253,43,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (254,43,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (255,43,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (256,43,'删除',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (257,43,'导入',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (258,43,'导出',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (44,12,'购物','/ResourceManage/Shopping/ShopList.aspx?sl=44',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (259,44,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (260,44,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (261,44,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (262,44,'删除',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (263,44,'导入',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (264,44,'导出',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (45,12,'保险','/ResourceManage/Insurance/Insurance.aspx?sl=45',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (265,45,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (266,45,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (267,45,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (268,45,'删除',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (269,45,'导入',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (270,45,'导出',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (46,12,'其它','/ResourceManage/Other/OtherList.aspx?sl=46',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (271,46,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (272,46,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (273,46,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (274,46,'删除',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (275,46,'导入',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (276,46,'导出',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (47,12,'线路资源','/ResourceManage/Path/PathList.aspx?sl=47',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (277,47,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (278,47,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (279,47,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (280,47,'删除',0,'1')
		

INSERT INTO [tbl_SysPrivs1]([Id],[Name],[SortId],[IsEnable],[ClassName]) VALUES (13,'合同管理',0,'1','hetonggl')	
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (48,13,'合同管理','/ContractManage/ContractNumList.aspx?sl=48',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (281,48,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (282,48,'登记',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (422,48,'销号',0,'1')
		
INSERT INTO [tbl_SysPrivs1]([Id],[Name],[SortId],[IsEnable],[ClassName]) VALUES (14,'账务管理',0,'1','caiwugl')
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (49,14,'单团核算','/FinanceManage/OneTeamAdjustAccounts/WaitList.aspx?sl=49',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (283,49,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (284,49,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (285,49,'其它收入添加',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (286,49,'其它支出添加',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (287,49,'利润分配添加',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (288,49,'核算结束',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (289,49,'退回计调',0,'1')
		
	
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (50,14,'应收管理','/FinanceManage/Receivable/ReceivableList.aspx?sl=50',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (290,50,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (291,50,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (292,50,'确认合同金额',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (293,50,'收款登记',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (294,50,'收款审核',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (295,50,'退款登记',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (296,50,'退款审核',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (297,50,'查看当日收款',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (51,14,'杂费收入','/FinanceManage/IncidentalExpenses/IncomeList.aspx?sl=51',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (298,51,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (299,51,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (300,51,'收入登记',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (301,51,'收入审核',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (52,14,'应付管理','/FinanceManage/Payable/PayableList.aspx?sl=52',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (302,52,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (303,52,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (304,52,'付款登记',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (305,52,'付款审批',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (306,52,'账务支付',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (307,52,'成本确认',0,'1')
	
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (53,14,'杂费支出','/FinanceManage/IncidentalExpenses/PayList.aspx?sl=53',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (308,53,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (309,53,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (310,53,'支出登记',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (311,53,'支出审核',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (54,14,'借款管理','/FinanceManage/Loan/List.aspx?sl=54',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (312,54,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (313,54,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (314,54,'借款审批',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (315,54,'账务支付',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (55,14,'报销报账','/FinanceManage/Apply/List.aspx?sl=55',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (316,55,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (317,55,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (318,55,'报销审批',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (319,55,'账务支付',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (56,14,'欠款预警','/FinanceManage/Arrearage/ClientList.aspx?sl=56',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (320,56,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (321,56,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (322,56,'超限审批',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (57,14,'批量销账','/FinanceManage/WriteOff/List.aspx?sl=57',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (323,57,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (324,57,'查看全部',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (325,57,'到款登记',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (326,57,'销售销账',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (58,14,'往来对账','/FinanceManage/ComeAndGoReconciliation/GatheringList.aspx?sl=57',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (327,58,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (328,58,'查看全部',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (59,14,'账务统计','/FinanceManage/Statistics/ProfitList.aspx?sl=59',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (329,59,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (330,59,'查看全部',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (60,14,'固定资产','/FinanceManage/FixedAssets/List.aspx?sl=60',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (331,60,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (332,60,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (333,60,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (334,60,'删除',0,'1')
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (94,60,'导出金蝶报表','/FinanceManage/Kingdee/List.aspx?sl=94',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (438,94,'栏目',0,'1','1')
		
	
INSERT INTO [tbl_SysPrivs1]([Id],[Name],[SortId],[IsEnable],[ClassName]) VALUES (15,'统计分析',0,'1','tongjifx')		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (61,15,'供应商流量统计','/StatisticAnalysis/Supplier/LocalAgencyList.aspx?sl=61',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (335,61,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (336,61,'查看全部',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (62,15,'线路流量统计','/StatisticAnalysis/RouteFlow/RouteFlowList.aspx?sl=62',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (337,62,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (338,62,'查看全部',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (63,15,'部门业绩统计','/StatisticAnalysis/Department/DepartmentList.aspx?sl=63',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (339,63,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (340,63,'查看全部',0,'1')		
	
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (64,15,'个人业绩统计','/StatisticAnalysis/Personal/PersonalList.aspx?sl=64',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (341,64,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (342,64,'查看全部',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (65,15,'客户交汇统计','/StatisticAnalysis/Customer/CustomerList.aspx?sl=65',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (343,65,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (344,65,'查看全部',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (66,15,'垫款余额表','/StatisticAnalysis/Advance/AdvanceList.aspx?sl=66',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (345,66,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (346,66,'查看全部',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (67,15,'收入对账单','/StatisticAnalysis/Reconciliations/IncomeList.aspx?sl=67',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (347,67,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (348,67,'查看全部',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (68,15,'支出对账单','/StatisticAnalysis/Reconciliations/ExpensesList.aspx?sl=68',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (349,68,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (350,68,'查看全部',0,'1')
	
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (69,15,'收入成本毛利表','/StatisticAnalysis/GrossProfit/GrossProfitList.aspx?sl=69',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (351,69,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (352,69,'查看全部',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (70,15,'账龄分析表','/StatisticAnalysis/AgingAnalys/AgingAnalysisList.aspx?sl=70',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (353,70,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (354,70,'查看全部',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (71,15,'状态查询表','/StatisticAnalysis/TourStatus/TourStatusList.aspx?sl=71',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (355,71,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (356,71,'查看全部',0,'1')
		
		
		
		
		
INSERT INTO [tbl_SysPrivs1]([Id],[Name],[SortId],[IsEnable],[ClassName]) VALUES (16,'行政中心',0,'1','xingzzx')

	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (72,16,'通知公告','/ManageCenter/Notice/NoticeList.aspx?sl=72',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (357,72,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (358,72,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (359,72,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (360,72,'删除',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (73,16,'职务管理','/ManageCenter/Duty/DutyList.aspx?sl=73',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (361,73,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (362,73,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (363,73,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (364,73,'删除',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (74,16,'规章制度','/ManageCenter/Rule/RuleList.aspx?sl=74',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (365,74,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (366,74,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (367,74,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (368,74,'删除',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (75,16,'会议记录','/ManageCenter/Meet/MeetList.aspx?sl=75',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (369,75,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (370,75,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (371,75,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (372,75,'删除',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (91,16,'考勤管理','/ManageCenter/Attendance/AttList.aspx?sl=91',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (373,91,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (374,91,'登记',0,'1')

	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (76,16,'内部通讯录','/ManageCenter/Contact/ContactList.aspx?sl=76',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (375,76,'栏目',0,'1','1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (77,16,'组织机构','/ManageCenter/Organize/OrgList.aspx?sl=77',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (376,77,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (377,77,'设置',0,'1')
	
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (78,16,'人事档案','/ManageCenter/Hr/HrList.aspx?sl=78',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (378,78,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (379,78,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (380,78,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (381,78,'删除',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (79,16,'物品管理','/ManageCenter/ObjectManage/ObjList.aspx?sl=79',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (382,79,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (383,79,'物品入库栏目',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (384,79,'入库操作',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (385,79,'物品领用栏目',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (386,79,'领用操作',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (387,79,'物品发放栏目',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (388,79,'发放操作',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (389,79,'物品借阅栏目',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (390,79,'借阅操作',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (80,16,'意见建议箱','/ManageCenter/Advice/AdviceList.aspx?sl=80',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (391,80,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (392,80,'提交',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (393,80,'处理',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (81,16,'员工离职','/ManageCenter/Leave/LeaveList.aspx?sl=81',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (394,81,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (395,81,'离职申请',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (396,81,'离职审批',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (82,16,'公司合同','/ManageCenter/Pack/PackList.aspx?sl=82',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (397,82,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (398,82,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (399,82,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (400,82,'删除',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (83,16,'培训管理','/ManageCenter/Train/TrainList.aspx?sl=83',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (401,83,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (402,83,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (403,83,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (404,83,'删除',0,'1')
		
	

INSERT INTO [tbl_SysPrivs1]([Id],[Name],[SortId],[IsEnable],[ClassName]) VALUES (17,'系统设置',0,'1','xitongsz')
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (84,17,'系统信息','/SystemSet/SystemConfig.aspx?sl=84',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (405,84,'栏目',0,'1','1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (85,17,'角色管理','/SystemSet/RoleList.aspx?sl=85',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (406,85,'栏目',0,'1','1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (86,17,'用户管理','/SystemSet/UserList.aspx?sl=86',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (407,86,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (408,86,'新增',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (409,86,'修改',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (410,86,'删除',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (411,86,'授权',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (87,17,'基础设置','/SystemSet/CityList.aspx?sl=87',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (412,87,'栏目',0,'1','1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (413,87,'城市管理栏目',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (414,87,'线路区域栏目',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (415,87,'报价标准栏目',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (416,87,'支付方式栏目',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (417,87,'上车地点栏目',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (418,87,'模板管理栏目',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (439,87,'客户等级栏目',0,'1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (88,17,'系统配置','/SystemSet/PrintConfig.aspx?sl=88',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (419,88,'栏目',0,'1','1')
		
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (89,17,'系统日志','/SystemSet/OperationLog.aspx?sl=89',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable],[IsMenu]) VALUES (420,89,'栏目',0,'1','1')
		
INSERT INTO [tbl_SysPrivs1]([Id],[Name],[SortId],[IsEnable]) VALUES (18,'个人中心',0,'1')
	INSERT INTO [tbl_SysPrivs2]([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES (92,18,'事务提醒','javascript:void(0)',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (423,92,'订单提醒',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (424,92,'计调提醒',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (425,92,'出团提醒',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (426,92,'回团提醒',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (427,92,'收款提醒',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (428,92,'付款提醒',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (429,92,'计调变更提醒',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (430,92,'预控到期提醒',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (431,92,'劳动合同到期提醒',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (432,92,'物品借阅到期提醒',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (433,92,'生日提醒',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (434,92,'公告提醒',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (435,92,'询价提醒',0,'1')
		INSERT INTO [tbl_SysPrivs3]([Id],[ParentId],[Name],[SortId],[IsEnable]) VALUES (436,92,'弹窗提醒',0,'1')
GO
