--生成日期 2012-05-23
SET IDENTITY_INSERT [tbl_SysPrivs2] ON

INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 1,1,'团队报价','/TeamCenter/PriceList.aspx?type=1&sl=1',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 2,1,'派团计划','/TeamCenter/TeamplanList.aspx?type=1&sl=2',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 3,1,'组团散拼','/TeamCenter/SanpinList.aspx?type=1&sl=3',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 4,2,'团队报价','/TeamCenter/PriceList.aspx?type=2&sl=4',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 5,2,'派团计划','/TeamCenter/TeamplanList.aspx?type=2&sl=5',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 6,2,'组团散拼','/TeamCenter/SanpinList.aspx?type=2&sl=6',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 7,3,'团队报价','/TeamCenter/PriceList.aspx?type=3&sl=7',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 8,3,'派团计划','/TeamCenter/TeamplanList.aspx?type=3&sl=8',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 9,3,'组团散拼','/TeamCenter/SanpinList.aspx?type=3&sl=9',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 10,4,'收客计划','/SellCenter/CustomerPlan/CustomerPlan.aspx?sl=10',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 11,4,'订单中心','/SellCenter/Order/OrderList.aspx?sl=11',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 12,5,'销售收款','/MarketCenter/XiaoShouShouKuan.aspx?&sl=12',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 13,5,'销售报账','/MarketCenter/XiaoShouBaoZhang.aspx?&sl=13',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 14,5,'预付确认','/MarketCenter/YuFuQueRen.aspx?&sl=14',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 15,5,'销售预警','/MarketCenter/XiaoShouYuJing.aspx?&sl=15',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 16,6,'单项业务','/SingleServe/SingleServerList.aspx?sl=16',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 17,7,'组团计调','/OperaterCenter/TeamOperaterList.aspx?sl=17',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 18,7,'地接计调','/OperaterCenter/TeamOperaterList.aspx?sl=18',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 19,7,'出境计调','/OperaterCenter/TeamOperaterList.aspx?sl=19',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 20,7,'业务变更','/OperaterCenter/OperationChange.aspx?sl=20',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 21,7,'计调报账','/OperaterCenter/OperaReimbursement.aspx?sl=21',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 22,7,'计调终审','/OperaterCenter/OperaterLastInstace.aspx?sl=22',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 23,8,'导游档案','/GuideCenter/GuideRecord.aspx?sl=23',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 24,8,'导游排班','/GuideCenter/GuideSchedul.aspx?sl=24',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 25,8,'上团统计','/GuideCenter/GuiTourStatistics.aspx?sl=25',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 26,8,'导游报账','/GuideCenter/GuidReimbursement.aspx?sl=26',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 27,9,'酒店预控','/ResourceCenter/Tavern/List.aspx?sl=27',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 28,9,'车辆预控','/ResourceCenter/Car/List.aspx?sl=28',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 29,9,'游船预控','/ResourceCenter/LoosePulley/List.aspx?sl=29',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 30,10,'团队回访','/QualityCenter/TeamVisit/VisitList.aspx?sl=30',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 31,10,'投诉管理','/QualityCenter/Complaint/CompList.aspx?sl=31',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 32,11,'同行客户','/crmcenter/list.aspx?sl=32',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 33,11,'单位直客','/crmcenter/list.aspx?sl=33',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 34,11,'个人会员','/crmcenter/gerenhuiyuan/list.aspx?sl=34',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 35,12,'地接社','/ResourceManage/Ground/GroundList.aspx?sl=35',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 36,12,'酒店','/ResourceManage/Wineshop/WineshopList.aspx?sl=36',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 37,12,'餐馆','/ResourceManage/Hotle/HotleList.aspx?sl=37',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 38,12,'游轮','/ResourceManage/Cruise/CruiseList.aspx?sl=38',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 39,12,'车队','/ResourceManage/Car/CarList.aspx?sl=39',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 40,12,'票务','/ResourceManage/Ticket/TicketList.aspx?sl=40',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 41,12,'景点','/ResourceManage/ScenicSpots/ScenicSpotsList.aspx?sl=41',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 42,12,'购物','/ResourceManage/Shopping/ShopList.aspx?sl=42',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 43,12,'其它','/ResourceManage/Other/OtherList.aspx?sl=43',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 44,12,'线路资源','/ResourceManage/Path/PathList.aspx?sl=44',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 45,13,'合同管理','/ContractManage/ContractCodeList.aspx?sl=45',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 46,14,'单团核算','/FinanceManage/OneTeamAdjustAccounts/List.aspx?sl=46',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 47,14,'应收管理','/FinanceManage/Receivable/List.aspx?sl=47',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 48,14,'杂费收入','/FinanceManage/IncidentalExpenses/IncomeList.aspx?sl=48',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 49,14,'应付管理','/FinanceManage/Payable/PayableList.aspx?sl=49',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 50,14,'杂费支出','/FinanceManage/IncidentalExpenses/PayList.aspx?sl=50',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 51,14,'借款管理','/FinanceManage/Loan/List.aspx?sl=51',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 52,14,'报销报账','/FinanceManage/Apply/List.aspx?sl=52',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 53,14,'发票管理','/FinanceManage/InvoiceManage/List.aspx?sl=53',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 54,14,'欠款预警','/FinanceManage/Arrearage/ClientList.aspx?sl=54',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 55,14,'往来对账','/FinanceManage/ComeAndGoReconciliation/GatheringList.aspx?sl=55',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 56,14,'财务统计','/FinanceManage/Statistics/ProfitList.aspx?sl=56',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 57,14,'金蝶报表','/FinanceManage/Kingdee/StatementsList.aspx?sl=57',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 58,14,'固定资产','/FinanceManage/FixedAssets/List.aspx?sl=58',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 59,15,'线路流量统计','/TongJi/Route.aspx?sl=59',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 60,15,'部门业绩统计','/TongJi/Department.aspx?sl=60',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 61,15,'个人业绩统计','/TongJi/Personal.aspx?sl=61',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 62,15,'收入对账单','/TongJi/Income.aspx?sl=62',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 63,15,'销售预警表','/FinanceManage/Arrearage/ClientList.aspx?sl=63',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 64,15,'状态查询表','/TongJi/QueryState.aspx?sl=64',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 65,15,'游客统计表','/TongJi/Traveller.aspx?sl=65',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 66,16,'通知公告','/ManageCenter/Notice/NoticeList.aspx?sl=66',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 67,16,'职务管理','/ManageCenter/Duty/DutyList.aspx?sl=67',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 68,16,'规章制度','/ManageCenter/Rule/RuleList.aspx?sl=68',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 69,16,'会议管理','/ManageCenter/Meet/MeetList.aspx?sl=69',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 70,16,'考勤管理','/ManageCenter/Attendance/AttList.aspx?sl=70',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 71,16,'内部通讯录','/ManageCenter/Contact/ContactList.aspx?sl=71',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 72,16,'组织机构','/ManageCenter/Organize/OrgList.aspx?sl=72',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 73,16,'人事档案','/ManageCenter/Hr/HrList.aspx?sl=73',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 74,16,'物品管理','/ManageCenter/ObjectManage/ObjList.aspx?sl=74',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 75,16,'员工离职','/ManageCenter/Leave/LeaveList.aspx?sl=75',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 76,16,'公司合同','/ManageCenter/Pack/PackList.aspx?sl=76',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 77,16,'培训管理','/ManageCenter/Train/TrainList.aspx?sl=77',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 78,16,'文件管理','/ManageCenter/File/FileList.aspx?sl=78',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 79,17,'系统信息','/SystemSet/SystemConfig.aspx?sl=79',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 80,17,'角色管理','/SystemSet/RoleList.aspx?sl=80',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 81,17,'用户管理','/SystemSet/UserList.aspx?sl=81',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 82,17,'基础设置','/SystemSet/CityList.aspx?sl=82',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 83,17,'系统配置','/SystemSet/PrintConfig.aspx?sl=83',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 84,17,'操作日志','/SystemSet/LoginLog.aspx?sl=84',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 85,18,'事务提醒','/UserCenter/WorkAwake /OrderRemind.aspx?sl=85',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 86,18,'公告通知','/UserCenter/Notice /NoticeList.aspx?sl=86',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 87,18,'工作交流','/UserCenter/WorkExchange/WorkReportList.aspx?sl=87',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 88,19,'短信中心','javascript:void(0);',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 89,14,'金蝶科目','/FinanceManage/KingdeeSubject/SubjectManageList.aspx?sl=89',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 90,9,'景点预控','/ResourceCenter/Sight/List.aspx?sl=90',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 91,9,'其他预控','/ResourceCenter/Other/List.aspx?sl=91',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 92,14,'代收管理','/FinanceManage/DaiShou/List.aspx?sl=92',0,'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 93,16,N'学习交流',N'/ManageCenter/Study/StudyList.aspx?sl=93',0,N'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 94,15,N'预算表',N'/TongJi/YuSuanBiao.aspx?sl=94',0,N'1')


INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 95,20,N'基础信息',N'/YouLun/JiChuXinXi.aspx?sl=95',0,N'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 96,20,N'资源扩展',N'/YouLun/ZiYuan.aspx?sl=96',0,N'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 97,20,N'航期管理',N'/YouLun/HangQi.aspx?sl=97',0,N'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 98,20,N'订单管理',N'/YouLun/DingDan.aspx?sl=98',0,N'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 99,20,N'会员管理',N'/YouLun/HuiYuan.aspx?sl=99',0,N'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 100,20,N'网站介绍',N'/YouLun/WangZhan.aspx?sl=100',0,N'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 101,20,N'资讯管理',N'/YouLun/ZiXun.aspx?sl=101',0,N'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 102,20,N'广告管理',N'/YouLun/GuangGao.aspx?sl=102',0,N'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 103,20,N'会议管理',N'/YouLun/HuiYi.aspx?sl=103',0,N'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 104,20,N'团购管理',N'/YouLun/TuanGou.aspx?sl=104',0,N'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 105,20,N'积分兑换',N'/YouLun/JiFenDuiHuan.aspx?sl=105',0,N'1')
INSERT [tbl_SysPrivs2] ([Id],[ParentId],[Name],[Url],[SortId],[IsEnable]) VALUES ( 106,20,N'礼品卡管理',N'/YouLun/LiPinKa.aspx?sl=106',0,N'1')
SET IDENTITY_INSERT [tbl_SysPrivs2] OFF



--生成二级栏目枚举SQL语句（将查询结果集另存为.txt文件即可）：
SELECT '/// <summary>
/// '+Menu1Name+'_'+Menu2Name+'
/// </summary>
'+Menu1Name+'_'+Menu2Name+' = '+CAST(Menu2Id AS VARCHAR(50))+','
FROM(SELECT A.Id AS Menu2Id,A.Name AS Menu2Name,B.Name AS Menu1Name FROM tbl_SysPrivs2 AS A INNER JOIN tbl_SysPrivs1 AS B ON A.ParentId=B.Id)C
